/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function compress(data: string | Buffer, dict?: string | Buffer | undefined | null): Promise<Buffer> | Promise<Buffer>
export function decompress(data: string | Buffer, dict?: string | Buffer | undefined | null): Promise<Buffer> | Promise<Buffer>
export function decompressSync(data: string | Buffer, dict?: string | Buffer | undefined | null): Buffer
export function compressSync(data: string | Buffer, dict?: string | Buffer | undefined | null): Buffer
